Fix crash ios.
Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSGenericException Reason: Unable to activate constraint with anchors <NSLayoutYAxisAnchor:0x600002808b80 "UITableView:0x7f8e7f27b000.top"> and <NSLayoutYAxisAnchor:0x600002808d00 "UITextField:0x7f8e7a78ee00.bottom"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal.

Disable auto correct.

Upgrade forms.